### PR TITLE
Compilation fixes on Linux

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Related to: https://github.com/azerothcore/mod-npc-talent-template/issues/4

The big compilation error might be related to this (but I really don't think so):
https://github.com/azerothcore/azerothcore-wotlk/pull/1338

@Winfidonarleyan what do you think?

https://github.com/azerothcore/azerothcore-wotlk/search?q=AddGossipItemFor&unscoped_q=AddGossipItemFor

we have this in the header though `#include "ScriptedGossip.h"` so it should be fine normally

**Note: I haven't tested anything lol, not even compilation**

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Also if someone else than me merges it, don't squash commits because the commits are not all for the same issue

**Comment by ide1234000** [comment]
Compile successfully but npc doesn't have any options in game

**Comment by BarbzYHOOL** [comment]
o_0 but I didn't touch the scripts
My only change is that: https://github.com/azerothcore/mod-npc-talent-template/pull/8/commits/54725c05ff4e69a4ee466d774405ae6f5019bb53

**Comment by BarbzYHOOL** [comment]
@mindsear any idea if I broke something? apparently it compiles now at least

**Comment by mindsear** [comment]
I don't have a lot of free time right now. I will test this in a few days or so.
I guess I'll have to install linux on a vm or something.

**Comment by mindsear** [comment]
So, I tried Barbz modified script on windows and it's still working.

Unfortunately, I don't have a linux machine lying around nor a linux vps.
For those having a linux vps and they wanna try Barbz modified script, please update your azerothcore and try again.

**Comment by BarbzYHOOL** [comment]
Ok @mindsear thank you, I guess I can merge it until we find the solution for linux

I just need to fix the conflicts unless you want to edit my PR directly lol (I'm not a C++ dev)

**Comment by mindsear** [comment]
Managed to get my hands on a linux vps. I'll try your fixes and report back.

**Comment by ide1234000** [comment]
Screenshot from 2019-03-13 17-02-19
got this when compiling on Ubuntu

**Comment by mindsear** [comment]
Alright, I've cloned a fresh azerothcore on my linux vps. Cloned your branch and so far I got one error

alt_tag

Now we have to edit template_scripts_loader.h
Basically, we need to change "AddTemplateScripts" to "AddTemplateNPCScripts".

***

I figured out why we get those linux errors.
If you take a look into [**npc_professions.cpp**](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/World/npc_professions.cpp#L395) they still use "player->ADD_GOSSIP_ITEM" instead of "AddGossipItemFor".
Same goes for "SendGossipMenuFor", "ClearGossipMenuFor" and "CloseGossipMenuFor".

Lastly, we need to remove this line
> AC_ADD_CONFIG_FILE("${CMAKE_CURRENT_LIST_DIR}/conf/TemplateNPC.conf.dist")

from **mod-npc-talent-template\CmakeLists.txt**

**Comment by BarbzYHOOL** [comment]
@ide1234000 you compiled previously and it worked lol, no update have been done to the PR


@mindsear alright, hmm do you want to edit my PR directly? I guess you can

And why do we need these changes? I know there was a big commit about GOSSIP stuff. And for the config file, are you sure? because we still have this in the skeleton module (aka template) https://github.com/azerothcore/skeleton-module/blob/master/CMakeLists.txt

**Comment by mindsear** [comment]
We don't need that line in CMakeLists.txt because this script doesn't need a configuration file. 
And we get 1 error on compilation on both linux and windows.

alt_tag

alt_tag

I will edit your PR , merge and close issue #4.

**Pull request merged**
