### PR TITLE
Update TemplateNPC.cpp

### PR DESCRIPTION
**Pull request by poszer**
- Fix issue with Mana & Health

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Hey thank you but what was the issue?

**Comment by poszer** [comment]
> Hey thank you but what was the issue?

It was set to 100 mana even if you have let's say 23k

**Comment by BarbzYHOOL** [comment]
Ah ok the NPC also heals you and refills your mana for immediate fighting?!

Nice, thank you for the PR, guess it can be merged then!

**Comment by poszer** [comment]
> Ah ok the NPC also heals you and refills your mana for immediate fighting?!

Yep. Once you learn talents and equip gear, your health will refills. 
PR can be merged. But i'll suggest to write something about this Modules, since it's gamebreaking.
Talents are not granted as talents, they re granted as Spells. 
So, when player interact with this NPC, and Equip & Learn talents, actually he's learning spells, without spending any talent points (At the end, you will have all class spells learned, and you can use them, but your talents will be untouched ( 0 spent , 79 can be spent ) --> Giving us option to use 2 Spec

**Comment by BarbzYHOOL** [comment]
o_0 that's completely broken

it's unusable

**Comment by milestorme** [comment]
Yeah basically it is unusable as it is , see open issue https://github.com/azerothcore/mod-npc-talent-template/issues/11

**Pull request merged**
