### PR TITLE
Add Spanish Clients Support.

### PR DESCRIPTION
**Pull request by ernesto-glz**
Basically, separate the menu definitions in a header file to keep the main file a little more decoupled, attached to this I have added the condition `` hasSpanishClient '' to each of the texts that are launched so that it detects the language of the client .
This only works, after https://github.com/azerothcore/azerothcore-wotlk/commit/92668be4f34ed740c40857c1bc328fd35d9ec38a

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
Please use new gossip API

**Comment by ErnestoGonzalezC** [comment]
@Winfidonarleyan Done, if there is anything else that needs to change, let me know.

**Comment by ErnestoGonzalezC** [comment]
@Helias Please check this pr who has been sleeping for 2 weeks :)

**Comment by Helias** [comment]
sorry, but... I don't really like this structure of doing the multi-lang.

I strongly suggest you to make an map/hashmap, so a dictionary and use that to change only the TRANSLATION TEXT.
Example:
```C++
languages.cpp
const translations  HashMap<string, HashMap<string, string>> = {
   "en": {
      "hello": "hello"
      .... and so on ...
    },
   "es": {
      "hello": "ola"
      .... and so on ...
  }
};
```
and use in the code:
```C++
// config
const LANG = "en";
...

//
gossip...( translations[LANG]["hello"] );
```

Another approach can consist of using the database for translations but if you want to make it by code and you have time I strongly suggest you to use the approach above

**Comment by Winfidonarleyan** [comment]
https://github.com/WarheadCore/Warhead/blob/master/src/server/game/Locale/ModuleLocale.cpp

**Comment by Winfidonarleyan** [comment]
> sorry, but... I don't really like this structure of doing the multi-lang.
> 
> I strongly suggest you to make an map/hashmap, so a dictionary and use that to change only the TRANSLATION TEXT.
> Example:
> 
> ```c++
> languages.cpp
> const translations  HashMap<string, HashMap<string, string>> = {
>    "en": {
>       "hello": "hello"
>       .... and so on ...
>     },
>    "es": {
>       "hello": "ola"
>       .... and so on ...
>   }
> };
> ```
> 
> and use in the code:
> 
> ```c++
> // config
> const LANG = "en";
> ...
> 
> //
> gossip...( translations[LANG]["hello"] );
> ```
> 
> Another approach can consist of using the database for translations, but if you want to make it by code and you have time I strongly suggest you to use the approach above because if we need to add another language currently we need to add more if else if / else structure, meanwhile we could just add a `"new"` key in the `translations`dictionary.
> 
> https://stackoverflow.com/questions/3578083/what-is-the-best-way-to-use-a-hashmap-in-c

i'm impelement modules locale :D

https://github.com/WarheadCore/Warhead/blob/master/src/server/game/Locale/ModuleLocale.cpp

**Comment by Helias** [comment]
this seems fantastic, but we need an example and some documentation to use it.

@ErnestoGonzalezC if you need this PR merged, we can do it and create an issue to migrate your multi-lang style into the Winfidonarleyan one that seems to work with the database and I think it's an optimal solution.

@Winfidonarleyan I think that we strongly need this with documentation.

**Comment by ErnestoGonzalezC** [comment]
> esto parece fantástico, pero necesitamos un ejemplo y algo de documentación para usarlo.
> 
> @ErnestoGonzalezC si necesita fusionar este PR, podemos hacerlo y crear un problema para migrar su estilo de varios idiomas al de Winfidonarleyan que parece funcionar con la base de datos y creo que es una solución óptima.
> 
> @Winfidonarleyan Creo que necesitamos esto con documentación.

It is not necessary I can wait for @@ Winfidonarleya to create a wiki for his method and migrate mine there :)

**Pull request closed without merging**
