### PR TITLE
fix: there's no templates for % specialization yet, closes #39

### LINKED ISSUE #39: "There's no templates for % specialization yet"
When adding the NPC in the game, it doesn't do the function, it just appears this message above, "There are still no templates for % of specialization". How can I fix it? Is it necessary to enable Gossip on the NPC?

[https://ibb.co/Hn1zFbd](url)

### PR DESCRIPTION
**Pull request by Diablosstars**
All SQL calls were Querying the data base with the %s literals within the query. With FMT, changing to '{}' allows for the variables to be formatted into the strings for all queries.

closes #39

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
Thanks for your PR, please, fix this error

```
[ 21%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o
/home/runner/work/mod-npc-talent-template/mod-npc-talent-template/modules/mod-npc-talent-template/src/TemplateNPC.cpp:936:109: fatal error: data argument not used by format string [-Wformat-extra-args]
            player->GetSession()->SendAreaTriggerMessage("There's no templates for {} specialization yet.", playerSpecStr.c_str());
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:90: modules/CMakeFiles/modules.dir/mod-npc-talent-template/src/TemplateNPC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1508: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by AnchyDev** [comment]
> Thanks for your PR, please, fix this error
> 
> ```
> [ 21%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o
> /home/runner/work/mod-npc-talent-template/mod-npc-talent-template/modules/mod-npc-talent-template/src/TemplateNPC.cpp:936:109: fatal error: data argument not used by format string [-Wformat-extra-args]
>             player->GetSession()->SendAreaTriggerMessage("There's no templates for {} specialization yet.", playerSpecStr.c_str());
>                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
> 1 error generated.
> make[2]: *** [modules/CMakeFiles/modules.dir/build.make:90: modules/CMakeFiles/modules.dir/mod-npc-talent-template/src/TemplateNPC.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1508: modules/CMakeFiles/modules.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```
There is the incorrect assumption that `SendAreaTrigger` uses `fmt::format`, however it uses `vsnprinf`. 
Reverting the change for those calls should fix the issue. I have created a [pull request](https://github.com/Diablosstars/mod-npc-talent-template/pull/1) on the Diablosstars branch.

**Comment by Helias** [comment]
thanks for the PR!

**Comment by EricksOliveira** [comment]
Tested and it's ok

**Comment by Helias** [comment]
The build is failing here, if this issue will be fixed I can merge the PR
```
/home/runner/work/mod-npc-talent-template/mod-npc-talent-template/modules/mod-npc-talent-template/src/TemplateNPC.cpp:936:109: fatal error: data argument not used by format string [-Wformat-extra-args]
            player->GetSession()->SendAreaTriggerMessage("There's no templates for {} specialization yet.", playerSpecStr.c_str());
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:90: modules/CMakeFiles/modules.dir/mod-npc-talent-template/src/TemplateNPC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1217: modules/CMakeFiles/modules.dir/all] Error 2
```

**Comment by AnchyDev** [comment]
> The build is failing here, if this issue will be fixed I can merge the PR
> 
> ```
> /home/runner/work/mod-npc-talent-template/mod-npc-talent-template/modules/mod-npc-talent-template/src/TemplateNPC.cpp:936:109: fatal error: data argument not used by format string [-Wformat-extra-args]
>             player->GetSession()->SendAreaTriggerMessage("There's no templates for {} specialization yet.", playerSpecStr.c_str());
>                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
> 1 error generated.
> make[2]: *** [modules/CMakeFiles/modules.dir/build.make:90: modules/CMakeFiles/modules.dir/mod-npc-talent-template/src/TemplateNPC.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1217: modules/CMakeFiles/modules.dir/all] Error 2
> ```

Still waiting on my PR merge on his branch that fixes this issue. If anybody would like to create a new PR with his changes and then cherry pick mine go ahead.

**Comment by Helias** [comment]
done https://github.com/azerothcore/mod-npc-talent-template/pull/43

I am closing this PR

**Pull request closed without merging**
