### PR TITLE
another fix: Belt prismatic socket bonuses don't get applied

### PR DESCRIPTION
**Pull request by ErnestoGonzalezC**

### CODE REVIEW

**Comment by Helias** [comment]
?

**Comment by ErnestoGonzalezC** [comment]
I thought it was my mistake :V

**Comment by ErnestoGonzalezC** [comment]
fails checks when trying to import

**Comment by ErnestoGonzalezC** [comment]
could check this pull request https://github.com/azerothcore/mod-npc-talent-template/pull/31

**Pull request closed without merging**
