### PR TITLE
Update TemplateNPC.cpp

### PR DESCRIPTION
**Pull request by mindsear**
Fixes https://github.com/azerothcore/mod-npc-talent-template/issues/6

### CODE REVIEW

**Comment by poszer** [comment]
Nice @mindsear. Will test it when i come home

**Comment by BarbzYHOOL** [comment]
Thank you mindsear!

**Comment by BarbzYHOOL** [comment]
Ah cool you added all the commits and didn't squash them so we get full history @mindsear  ;)

**Comment by poszer** [comment]
Tested. Fully working now :D Thanks @mindsear

**Pull request merged**
